name: MeowOfLegends
version: '${project.version}'
main: unboxthecat.meowoflegends.MeowOfLegends
api-version: 1.19
authors: [ UnboxTheCat, Yarh ]
description: Meow Meow Meow Explosion!
website: https://github.com/evanhyd/MeowOfLegends
permissions:
  MeowOfLegends.debug:
    description: default permission for debug commands
    default: op
  MeowOfLegends.mana:
    description: default permission for mana commands
    default: op
  MeowOfLegends.health:
    description: default permission for health commands
    default: op
  MeowOfLegends.movement:
    description: default permission for movement commands
    default: op

commands:
  test:
    description: Custom testing command.
    usage: /<command>
    permission: MeowOfLegends.debug
    permission-message: You do not have permission!
  debug:
    description: Prints out relevant debug information.
    usage: /<command>
    permission: MeowOfLegends.debug
    permission-message: You do not have permission!
  manacomponent:
    description: Set mana component property by calling class function directly through reflection.
    usage: /<command>
    permission: MeowOfLegends.mana
    permission-message: You do not have permission!
  healthcomponent:
    description: Set health component property by calling class function directly through reflection.
    usage: /<command>
    permission: MeowOfLegends.health
    permission-message: You do not have permission!
  top:
    description: Teleport player to the highest block of the current location.
    usage: /<command>
    permission: MeowOfLegends.movement
    permission-message: You do not have permission!


