name: MeowOfLegends
version: '${project.version}'
main: unboxthecat.meowoflegends.MeowOfLegends
api-version: 1.19
authors: [ UnboxTheCat, Yarh ]
description: Meow Meow Meow Explosion!
website: https://github.com/evanhyd
permissions:
  MeowOfLegends.all:
    children:
      MeowOfLegends.debug: true
      MeowOfLegends.mana: true
commands:
  debug:
    description: Prints out relevant debug information
    usage: /<command>
    permission: MeowOfLegends.debug
    permission-message: You do not have permission!
  setcurrentmana:
    description: Sets current mana value
    usage: /<command>
    permission: MeowOfLegends.mana
    permission-message: You do not have permission!
  setmaxmana:
    description: Sets max mana value
    usage: /<command>
    permission: MeowOfLegends.mana
    permission-message: You do not have permission!
  setmanaregenerationrate:
    description: Sets mana regeneration rate value
    usage: /<command>
    permission: MeowOfLegends.mana
    permission-message: You do not have permission!


